cc.CCCONTROL_EVENT_TOUCH_DOWN           = 1 << 0;
cc.CCCONTROL_EVENT_TOUCH_DRAGINSIDE     = 1 << 1;
cc.CCCONTROL_EVENT_TOUCH_DRAGOUTSIDE    = 1 << 2;
cc.CCCONTROL_EVENT_TOUCH_DRAGENTER      = 1 << 3;
cc.CCCONTROL_EVENT_TOUCH_DRAGEXIT       = 1 << 4;
cc.CCCONTROL_EVENT_TOUCH_UP_INSIDE      = 1 << 5;
cc.CCCONTROL_EVENT_TOUCH_UP_OUTSIDE     = 1 << 6;
cc.CCCONTROL_EVENT_TOUCH_CANCEL         = 1 << 7;
cc.CCCONTROL_EVENT_VALUE_CHANGED        = 1 << 8;

cc.CCCONTROL_STATE_NORMAL       = 1 << 0;
cc.CCCONTROL_STATE_HIGHLIGHTED  = 1 << 1;
cc.CCCONTROL_STATE_DISABLED     = 1 << 2;
cc.CCCONTROL_STATE_SELECTED     = 1 << 3;
