/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c CCControl.jsb.ini" on 2013-01-12
* Script version: v0.3
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_CCCONTROL

#import "CCControlExtension.h"
#import "js_bindings_cocos2d_ios_classes.h"
#import "js_bindings_NS_manual.h"
#import "js_bindings_cocos2d_manual.h"

/*
 * CCControl
 */
#pragma mark - CCControl

#ifdef __cplusplus
extern "C" {
#endif

void JSB_CCControl_createClass(JSContext *cx, JSObject* globalObj, const char* name );

// Manually generated methods
JSBool JSB_CCControl_setBlock_forControlEvents_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_CCControl_openURL_(JSContext *cx, uint32_t argc, jsval *vp);


extern JSObject *JSB_CCControl_object;
extern JSClass *JSB_CCControl_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_CCControl : JSB_CCLayer
{
}
@end

/*
 * CCScale9Sprite
 */
#pragma mark - CCScale9Sprite

#ifdef __cplusplus
extern "C" {
#endif

void JSB_CCScale9Sprite_createClass(JSContext *cx, JSObject* globalObj, const char* name );



extern JSObject *JSB_CCScale9Sprite_object;
extern JSClass *JSB_CCScale9Sprite_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_CCScale9Sprite : JSB_CCNode
{
}
@end

/*
 * CCControlButton
 */
#pragma mark - CCControlButton

#ifdef __cplusplus
extern "C" {
#endif

void JSB_CCControlButton_createClass(JSContext *cx, JSObject* globalObj, const char* name );



extern JSObject *JSB_CCControlButton_object;
extern JSClass *JSB_CCControlButton_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_CCControlButton : JSB_CCControl
{
}
@end


#endif // JSB_INCLUDE_CCCONTROL
