/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c CCControl.jsb.ini" on 2013-01-12
* Script version: v0.3
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_CCCONTROL

#import "CCControlExtension.h"
#import "js_bindings_cocos2d_ios_classes.h"
#import "js_bindings_NS_manual.h"
#import "js_bindings_cocos2d_manual.h"
JSB_CCControl_createClass(_cx, CCControl, "Control");
JSB_CCControlButton_createClass(_cx, CCControl, "ControlButton");
JSB_CCScale9Sprite_createClass(_cx, CCControl, "Scale9Sprite");


#endif // JSB_INCLUDE_CCCONTROL
